name: CodeCheck

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      DB_HOST: ${{secrets.DB_HOST}}
      DB_PORT: ${{secrets.DB_PORT}}
      DB_DATABASE: ${{secrets.DB_DATABASE}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docker-compose up
        run: docker compose up -d

      - name: composer install
        run: docker-compose exec -T web bash -c "composer install"

      - name: phpunit
        run: docker-compose exec -T web bash -c "composer test"

      - name: php-cs-fixer
        run: docker-compose exec -T web bash -c "composer format_dry_run"

      - name: stan
        run: docker-compose exec -T web bash -c "composer stan"

      - name: md
        run: docker-compose exec -T web bash -c "composer md"
